version: '3'
services:
  backend:
    build: backend/ 
  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./frontend/fyberapi.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - 8081:80
